### ISSUE TITLE
KLA Json files

### ISSUE THREAD

**Issue by iandoug** [NotGate/layout#1]
Hi

Can you maybe post the KLA json files?

Thanks, Ian

**Comment by NotGate** [comment]
Sure thing. I uploaded the KLA files for the ANSI, Matrix, and Ergo versions. 
https://github.com/NotGate/layout/blob/gh-pages/isrt_ansi.json
https://github.com/NotGate/layout/blob/gh-pages/isrt_matrix.json
https://github.com/NotGate/layout/blob/gh-pages/isrt_ergo.json

**Comment by iandoug** [comment]
Thanks, appreciate it :-)
